apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
  labels:
    purpose: multi-container-demo
    project: roboshop
spec:
   containers:
   - name: nginx
     image: nginx
   - name: almalinux
     image: almalinux:9    