apiVersion: v1
kind: Pod
metadata:
  name: env-secret
  labels:
    purpose: secret-demo
    env: dev
spec:
   containers:
   - name: nginx
     image: nginx
     envFrom:
     - configMapRef:
          name: pod-secret

