apiVersion: v1
kind: Pod
metadata:
   name: resouces
   labels:
     project: roboshop
     env: dev
spec:
  containers:
  - name: nginx
    image: nginx
  resources:
    requests:
      memory: "60Mi"
      cpu: "100m"
    limits:
      memory: "180Mi"
      cpu: "150m"        