apiVersion: v1
kind: Service
metadata:
   name: service-np
   labels:
     purpose: service-demo
spec:
   type: NodePort
   selector:
     type: demo
     purpose: service-np-demo
     tier: frontend
   ports:
     - protocol: TCP
       port: 80
       targetPort: 80  
     

---
apiVersion: v1
kind: Pod
metadata: 
   name: nginx
   labels:
     type: demo
     purpose: service-np-demo
     tier: frontend
spec:
   containers:
    - name: nginx
      image: nginx       

